blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    #path('timesharer/myprofile/', include('user_profile.urls')),
    path('timesharer/', include('timesharer.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

timesharer/urls.py
from django.urls import path, include
from . import views

app_name = 'timesharer'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('organisations/<slug>/', views.tagged_organisations, name='tagged_organisations'),
    path('opportunities/<slug>/', views.tagged_opportunities, name='tagged_opportunities'),
    path('volunteer/<int:pk>/', views.VolunteerDetail.as_view(), name='volunteer_detail'),
    path('volunteer/create/', views.CreateVolunteer.as_view(), name='create_volunteer'),
    path('volunteer/<int:pk>/edit', views.EditVolunteer.as_view(), name='edit_volunteer'),
    path('volunteer/<int:pk>/delete', views.DeleteVolunteer.as_view(), name='delete_volunteer'),
    path('volunteer/<int:volunteer_id>/amend-live-status', views.amend_vol_live_status, name='amend_vol_status'),
    path('organisation/<int:pk>/', views.OrganisationDetail.as_view(), name='organisation_detail'),
    path('organisation/create/', views.CreateOrganisation.as_view(), name='create_organisation'),
    path('organisation/<int:pk>/edit', views.EditOrganisation.as_view(), name='edit_organisation'),
    path('organisation/<int:pk>/delete', views.DeleteOrganisation.as_view(), name='delete_organisation'),
    path('organisation/<int:organisation_id>/amend-live-status', views.amend_org_live_status, name='amend_org_status'),
    path('opportunity/<int:pk>/', views.OpportunityDetail.as_view(), name='opportunity_detail'),
    path('opportunity/create/', views.CreateOpportunity.as_view(), name='create_opportunity'),
    path('opportunity/<int:pk>/delete', views.DeleteOpportunity.as_view(), name='delete_opportunity'),
    path('opportunity/<int:pk>/edit', views.EditOpportunity.as_view(), name='edit_opportunity'),
    path('opportunity/<int:opportunity_id>/amend-live-status', views.amend_opp_live_status, name='amend_opp_status'),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'
urlpatterns = [
    path('', views.index, name='index'),
]

user_profile/models.py
from django.db import models

user_profile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from timesharer.models import Volunteer, Organisation, Opportunity
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
import datetime
from django.utils import timezone

@login_required
def index(request):
    user = request.user
    
    try:
        volunteer = Volunteer.objects.get(created_by=user.pk)
        
    except:
        volunteer = 'No volunteer'

    if volunteer != 'No volunteer':
        opportunities = Opportunity.objects.filter(pk=volunteer.pk)
        live_volunteer = volunteer.is_live
        print(volunteer)

    if volunteer == 'No volunteer':
        volunteer = {'error': 'No volunteer'}
        opportunities = {'error':'No opportunities'}
        live_volunteer = {'error': 'No volunteer'}
        print(volunteer)

    

    capitalised_name = user.first_name.capitalize()

    context = {
        'volunteer':volunteer,
        'opportunities':opportunities,
        'capitalised_name':capitalised_name,
        'live_volunteer': live_volunteer
    }
    return render(request, 'user_profile/index.html', context)

user_profile/templates/user_profile/index.html
{% extends 'core/profile_base.html' %}

{% if user.is_authenticated %}
    {% block profile_details %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde"style="width:150px" alt="...">
            
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{ user }}</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Email address: <strong>{{ user.email }}</strong></li>
                    <li class="list-group-item">Chosen name: <strong>{{ user.first_name }}</strong></li>
                    <li class="list-group-item">Family name: <strong>{{ user.last_name }}</strong></li>
                </ul>
                <div style="margin-top:5px;margin-bottom:10px">
                {% if volunteer %}
                    {% if volunteer.error %}
                        <a href="/timesharer/volunteer/create">
                            <button type="button" class="btn btn-primary">
                                Create your volunteer profile
                            </button>
                        </a>
                    {% else %}
                        <a href="{% url 'timesharer:volunteer_detail' volunteer.id %}">
                            <button type="button" class="btn btn-primary">
                                View your volunteer profile
                            </button>
                        </a>
                            <div style="margin-top:10px">
                            Volunteer profile is 
                            {% if live_volunteer == True %}
                            public 
                            <a href="{% url 'timesharer:amend_vol_status'  volunteer_id=volunteer.id %}"><span class="badge bg-danger">Hide</span></a>
                            {% else %}
                            hidden 
                            <a href="{% url 'timesharer:amend_vol_status' volunteer_id=volunteer.id %}" ><span class="badge bg-success">Show</span></a>
                            {% endif %}
                        </div>
                        </a>
                    {% endif %}
                    {% else %}
                        Sorry, something has gone wrong. Please try again.
                {% endif %}
                
                
                </div>
                <p class="card-text">
                  <small class="text-muted">
                      Last updated 
                        {% if recent %}
                            just now
                        {% else %}
                            {{ volunteer.updated_at|timesince }} ago
                        {% endif %}
                    </small>
                </p>
            </div>

          </div>

          
        </div>
      </div>
    
        
    {% endblock %}

{% endif %}

{% block opportunities %}
    {% if opportunities %}
        
        {% if opportunities.error %}
            None to show.
        {% else %}
        {% for opp in opportunities %}
        <div class="col">
            <div class="card h-100">
                <img src="https://images.unsplash.com/photo-1622115168398-af384a2b4d85?ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyfHx8ZW58MHx8fHw%3D&ixlib=rb-1.2.1" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ opp.title }}</h5>
                        <p>{{ opp.description }}</p>
                    </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
{% endif %}
{% endblock opportunities %}

{% block options %}
      
    
{% endblock %}