blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    #path('timesharer/myprofile/', include('user_profile.urls')),
    path('timesharer/', include('timesharer.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

blog/models.py
import datetime

from django.db import models
from django.utils import timezone

class Post(models.Model):
    post_title = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    post_author = models.CharField(max_length=10)
    post_body = models.TextField()

    def __str__(self):
        return self.post_title
    def recently_published(self):
        return self.pub_date >= timezone.now() - datetime.datetime(days=1)

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post


def index(request):
    latest_post_list = Post.objects.order_by('-pub_date')[:5]
    context = {
        'latest_post_list': latest_post_list,
    }
    return render(request, 'blog/index.html', context)

def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/post.html', { 'post': post })

blog/templates/blog/index.html
{% if latest_post_list %}
    <ul>
        {% for post in latest_post_list %}
            <li><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a> <i>{{ post.pub_date }}</i></li>
        {% endfor %}
    </ul>
{% else %}
    <p>
        No blog posts are available!
    </p>
    {% endif %}

blog/templates/blog/post.html
<h1>{{ post.post_title }}</h1>
<p>
    {{ post.post_author}}</br>
    {{ post.post_pub_date}}</br>
    {{ post.post_body }}
</p>