blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    #path('timesharer/myprofile/', include('user_profile.urls')),
    path('timesharer/', include('timesharer.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

timesharer/urls.py
from django.urls import path, include
from . import views

app_name = 'timesharer'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('organisations/<slug>/', views.tagged_organisations, name='tagged_organisations'),
    path('opportunities/<slug>/', views.tagged_opportunities, name='tagged_opportunities'),
    path('volunteer/<int:pk>/', views.VolunteerDetail.as_view(), name='volunteer_detail'),
    path('volunteer/create/', views.CreateVolunteer.as_view(), name='create_volunteer'),
    path('volunteer/<int:pk>/edit', views.EditVolunteer.as_view(), name='edit_volunteer'),
    path('volunteer/<int:pk>/delete', views.DeleteVolunteer.as_view(), name='delete_volunteer'),
    path('volunteer/<int:volunteer_id>/amend-live-status', views.amend_vol_live_status, name='amend_vol_status'),
    path('organisation/<int:pk>/', views.OrganisationDetail.as_view(), name='organisation_detail'),
    path('organisation/create/', views.CreateOrganisation.as_view(), name='create_organisation'),
    path('organisation/<int:pk>/edit', views.EditOrganisation.as_view(), name='edit_organisation'),
    path('organisation/<int:pk>/delete', views.DeleteOrganisation.as_view(), name='delete_organisation'),
    path('organisation/<int:organisation_id>/amend-live-status', views.amend_org_live_status, name='amend_org_status'),
    path('opportunity/<int:pk>/', views.OpportunityDetail.as_view(), name='opportunity_detail'),
    path('opportunity/create/', views.CreateOpportunity.as_view(), name='create_opportunity'),
    path('opportunity/<int:pk>/delete', views.DeleteOpportunity.as_view(), name='delete_opportunity'),
    path('opportunity/<int:pk>/edit', views.EditOpportunity.as_view(), name='edit_opportunity'),
    path('opportunity/<int:opportunity_id>/amend-live-status', views.amend_opp_live_status, name='amend_opp_status'),
]

timesharer/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils import timezone

class Organisation(models.Model):
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=20)
    is_live = models.BooleanField()
    tags = TaggableManager()
    created_at = models.DateTimeField('date created')
    owned_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    description = models.TextField(default='Description')
    def __str__(self):
        return self.name

class Opportunity(models.Model):
    title = models.CharField(max_length=20)
    location = models.CharField(max_length=20, default='Location')
    description = models.TextField(default='Description')
    is_live = models.BooleanField()
    owned_by = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    #volunteers = models.ForeignKey(Volunteer, on_delete=models.CASCADE, blank=True)
    tags = TaggableManager()
    created_at = models.DateTimeField('date created',default=timezone.now)
    def __str__(self):
        return self.title

class Volunteer(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=20)
    opted_in = models.BooleanField(default=False)
    created_at = models.DateTimeField('date created',default=timezone.now)
    updated_at = models.DateTimeField('date updated',default=timezone.now)
    is_live = models.BooleanField()
    applied_to = models.ForeignKey(Opportunity, on_delete=models.CASCADE, default="1")
    tags = TaggableManager()
    def __str__(self):
        return self.name

timesharer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.base import TemplateView
from .models import Volunteer, Opportunity, Organisation
from taggit.models import Tag
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .volunteer_service import Volunteer_Service
from .organisation_service import Organisation_Service
from .opportunity_service import Opportunity_Service


def tagged_organisations(request, slug):
    lower_case_slug = slug.lower()
    tag = get_object_or_404(Tag, slug=lower_case_slug)
    organisations = Organisation.objects.filter(tags=tag)[:5]
    context = {
        'tag':tag,
        'organisations':organisations
    }
    return render(request, 'timesharer/tagged_organisations.html', context)

def tagged_opportunities(request, slug):
    lower_case_slug = slug.lower()
    tag = get_object_or_404(Tag, slug=lower_case_slug)
    opportunities = Opportunity.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'opportunities':opportunities
    }
    return render(request, 'timesharer/tagged_opportunities.html', context)

@login_required
def amend_vol_live_status(request, volunteer_id):
    volunteer_service = Volunteer_Service(volunteer_id)
    volunteer = Volunteer.objects.get(pk=volunteer_id)
    if volunteer.is_live:
        volunteer_service.make_not_live()
        return redirect('user_profile:index')
    if volunteer.is_live == False:
        volunteer_service.make_live()
        return redirect('user_profile:index')

@login_required
def amend_org_live_status(request, organisation_id):
    organisation_service = Organisation_Service(organisation_id)
    organisation = Organisation.objects.get(pk=organisation_id)
    if organisation.is_live:
        organisation_service.make_not_live()
        return redirect('timesharer:organisation_detail',organisation_id)
    if organisation.is_live == False:
        organisation_service.make_live()
        return redirect('timesharer:organisation_detail',organisation_id)

@login_required
def amend_opp_live_status(request, opportunity_id):
    opportunity_service = Opportunity_Service(opportunity_id)
    opportunity = Opportunity.objects.get(pk=opportunity_id)
    if opportunity.is_live:
        opportunity_service.make_not_live()
        return redirect('timesharer:opportunity_detail', opportunity_id)
    if opportunity.is_live == False:
        opportunity_service.make_live()
        return redirect('timesharer:opportunity_detail', opportunity_id)


class IndexView(TemplateView):
    template_name = 'timesharer/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        public_volunteers = Volunteer.objects.filter(is_live=True).order_by('created_at')[:5]
        public_organisations = Organisation.objects.filter(is_live=True).order_by('-created_at')[:5]
        public_opportunities = Opportunity.objects.filter(is_live=True).order_by('-created_at')[:5]
        context['organisations'] = public_organisations
        context['opportunities'] = public_opportunities
        context['volunteers'] = public_volunteers
        return context

#OPPORTUNITY
class CreateOpportunity(LoginRequiredMixin,CreateView):
    model = Opportunity
    template_name = 'timesharer/opportunity/forms/create_opportunity.html'
    fields = ['title','is_live','owned_by']

class OpportunityDetail(generic.DetailView):
    model = Opportunity
    template_name = 'timesharer/opportunity/opportunity_detail.html'

class DeleteOpportunity(LoginRequiredMixin,generic.DeleteView):
    template_name = 'timesharer/opportunity/forms/delete_volunteer.html'

class EditOpportunity(LoginRequiredMixin,generic.UpdateView):
    model = Opportunity
    fields = ['title','location','description']
    template_name = 'timesharer/opportunity/forms/edit_opportunity.html'

#VOLUNTEER
class CreateVolunteer(LoginRequiredMixin,CreateView):
    model = Volunteer
    template_name = 'timesharer/volunteer/forms/create_volunteer.html'
    fields = ['name', 'location', 'opted_in', 'created_at', 'updated_at', 'is_live', 'applied_to']
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class VolunteerDetail(LoginRequiredMixin,generic.DetailView):
    model = Volunteer
    #recent = (updated_at - timezone.now()).seconds < 60
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url = self.request.get_full_path()
        vol_id = url.split('/')[3]
        
        if self.request.user.is_authenticated:
            username = self.request.user.username
            vol = Volunteer.objects.get(pk=vol_id)
            created_by = vol.created_by

        matched = False
        
        if str(created_by) == username:
            matched = True

        context['matched'] = matched
        return context
    

    template_name = 'timesharer/volunteer/volunteer_detail.html'

class DeleteVolunteer(LoginRequiredMixin,generic.DeleteView):
    template_name = 'timesharer/volunteer/forms/delete_volunteer.html'

class EditVolunteer(LoginRequiredMixin,generic.UpdateView):
    model = Volunteer
    fields = ['name','location','is_live','opted_in']
    template_name = 'timesharer/volunteer/forms/edit_volunteer.html'

#ORGANISATION
class CreateOrganisation(LoginRequiredMixin,CreateView):
    model = Organisation
    template_name = 'timesharer/organisation/forms/create_organisation.html'
    fields = ['name', 'location', 'is_live']

class OrganisationDetail(generic.DetailView):
    model = Organisation
    template_name = 'timesharer/organisation/organisation_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url = self.request.get_full_path()
        org_id = url.split('/')[3]
        
        if self.request.user.is_authenticated:
            username = self.request.user.username
            org = Organisation.objects.get(pk=org_id)
            owned_by = org.owned_by

        matched = False
        
        if str(owned_by) == username:
            matched = True

        context['matched'] = matched
        return context

class DeleteOrganisation(LoginRequiredMixin,generic.DeleteView):
    template_name = 'timesharer/organisation/forms/delete_organisation.html'

class EditOrganisation(LoginRequiredMixin,generic.UpdateView):
    model = Organisation
    fields = ['name','location','is_live','opportunity_set']
    template_name = 'timesharer/organisation/forms/edit_organisation.html'

timesharer/templates/timesharer/index.html
{% extends 'core/base_generic.html' %}

{% block content %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <h1 class="display-4 fst-italic">Welcome to TimeSharer</h1>
    <p class="lead my-3">If you volunteer your time, you want to be able to keep control of your personal information. </p>
    <p class="lead"><strong>With TimeSharer, you can.</strong></p>

</div>
{% endblock %}

{% block opportunities %}
<h5>Latest opportunities</h5>
{% if opportunities %}
    <div class="card-group">
        {% for o in opportunities %}
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'timesharer:opportunity_detail' o.id %} ">{{ o.title }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ o.owned_by }}</h6>
                {% for tag in o.tags.all %}
                    <a href="{% url 'timesharer:tagged_opportunities' tag.slug %}"><span class="badge bg-secondary">{{ tag }}</span></a>
                    {% endfor %}<br>
              </div>

              <div class="card-footer">
                <a href="{% url 'timesharer:opportunity_detail' o.id %} " class="card-link"><button type="button" class="btn btn-primary btn-sm"style="margin-top:5px">Register interest</button></a>
              </div>
            </div>
        {% endfor %}
    </div>
{% endif %}
           

{% endblock %}

{% block organisations %}
<h5>Latest organisations</h5>
{% if organisations.count > 0 %}
    <div class="card-group">
        {% for org in organisations %}
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'timesharer:organisation_detail' org.id %} ">{{ org.name }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ org.location }}</h6>
                {% for tag in org.tags.all %}
                    <a href="{%url 'timesharer:tagged_organisations' tag.slug %}"><span class="badge bg-secondary">{{ tag }}</span></a>
                    {% endfor %}<br> 
              </div>

              <div class="card-footer">
                <a href="{% url 'timesharer:organisation_detail' org.id %} " class="card-link"><button type="button" class="btn btn-primary btn-sm"style="margin-top:5px">Register interest</button></a>
              </div>
            </div>
        {% endfor %}
    </div>
{% else %}
  <div class="card">
    <div class="card-body">
      There are currently no publicly accessible volunteer profiles available. Please try again later.
    </div>
  </div>
{% endif %}
{% endblock %}

{% block volunteers %}
<h5>Latest volunteers</h5>
{% if volunteers.count > 0 %}
    <div class="card-group">
        {% for vol in volunteers %}
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'timesharer:volunteer_detail' vol.id %} ">{{ vol.name }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ vol.location }}</h6>
              </div>

              <div class="card-footer">
                
              </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="card">
      <div class="card-body">
        There are currently no publicly accessible volunteer profiles available. Please try again later.
      </div>
    </div>
{% endif %}
{% endblock %}

timesharer/templates/timesharer/organisation_detail.html
{% if organisation %}
    {{ organisation.name }}
{% endif %}

timesharer/templates/timesharer/tagged_opportunities.html
{% extends 'core/base_tagged.html' %}

{% block content %}
    {% if opportunities %}
        <div class="card-group">
            {% for o in opportunities %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ o.title }}</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ o.location }}</h6>
                        <p>{{ o.description }}</p>
                    </div>
    
                    <div class="card-footer">
                    <a href="{% url 'timesharer:opportunity_detail' o.id %} " class="card-link"><button type="button" class="btn btn-primary btn-sm"style="margin-top:5px">Register interest</button></a>
                    </div>
                </div>
            {% endfor %}
        </div>
        
    {% endif %}
{% endblock %}

timesharer/templates/timesharer/tagged_organisations.html
{% extends 'core/base_tagged.html' %}

{% block content %}
    {% if organisations %}
        <div class="card-group">
            {% for o in organisations %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ o.name }}</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ o.location }}</h6>
                    </div>
    
                    <div class="card-footer">
                    <a href="{% url 'timesharer:organisation_detail' o.id %} " class="card-link"><button type="button" class="btn btn-primary btn-sm"style="margin-top:5px">Register interest</button></a>
                    </div>
                </div>
            {% endfor %}
        </div>
        
    {% endif %}
{% endblock %}